CONFIG_DATASET_ROOT_DIR:str = 'dataset-root-dir'
CONFIG_SEQUENCE:str = 'sequence'
CONFIG_SEQUENCE_DIR:str = 'sequence-dir'
CONFIG_HDF5_PATH:str = 'hdf5-path'

FRAMEID_WORLD:str = 'world'
FRAMEID_POSE:str = 'pose'
FRAMEID_CAM0:str = 'cam0'
FRAMEID_CAM1:str = 'cam1'
FRAMEID_CAM2:str = 'cam2'
FRAMEID_CAM3:str = 'cam3'
FRAMEID_VELODYNE:str = 'velodyne'
FRAMEID_SICK:str = 'sick'
FRAMEID_OXTS_POSE:str = 'oxts_pose'
FRAMEID_OXTS_CAM0:str = 'oxts_cam0'
FRAMEID_OXTS_CAM1:str = 'oxts_cam1'
FRAMEID_OXTS_CAM2:str = 'oxts_cam2'
FRAMEID_OXTS_CAM3:str = 'oxts_cam3'
FRAMEID_OXTS_VELODYNE:str = 'oxts_velodyne'
FRAMEID_OXTS_SICK:str = 'oxts_sick'

LABEL_TAG:str = 'kitti360'

PLY_ELEMENT_VERTEX:str = 'vertex'
VOXELGRIDFILTER_LEAFSIZE:float = 0.2

DIR_IMAGE00:str = 'image_00'
DIR_IMAGE01:str = 'image_01'
DIR_DATA_RECT:str = 'data_rect'
DIR_DATA:str = 'data'
DIR_VELODYNE_POINTS:str = 'velodyne_points'
DIR_SICK_POINTS:str = 'sick_points'
DIR_CALIBRATION:str = 'calibration'
DIR_SEMANTIC:str = 'semantic'
DIR_OXTS:str = 'oxts'
DIR_TRAIN:str = 'train'
DIR_TEST:str = 'test'
